import type { Education, WorkExperience } from "~/types/experience";

export const experiences: WorkExperience[] = [
  {
    company: "Trendyol Go by Uber Eats",
    currentPosition: "Senior Software Engineer",
    period: "July 2025 - Present",
    location: "Remote",
    description:
      "Architecting and implementing high-performance delivery platform solutions. Spearheading cross-platform mobile and web development initiatives, establishing best practices for micro frontend architecture, and ensuring seamless integration across multiple service boundaries. Driving innovation in food and grocery delivery technology while maintaining system scalability and reliability.",
    technologies: [
      "Vue",
      "React",
      "React Native",
      "Astro",
      "TypeScript",
      "SCSS",
      "BEM Methodology",
      "Design System",
      "Web Components",
      "Lit",
      "Golang",
      "Kotlin",
      "Couchbase",
      "PostgreSQL",
      "Redis",
      "Kafka",
      "Microservice Architecture",
      "Microfrontend Architecture",
      "Docker",
      "Kubernetes",
      "Nginx",
      "Gitlab",
      "CI/CD",
      "Cypress",
      "Playwright",
      "Jest",
      "Vitest",
    ],
  },
  {
    company: "Trendyol Group",
    currentPosition: "Senior Software Engineer",
    period: "July 2021 - July 2025",
    location: "Remote",
    description:
      "Lead the design and development of scalable software solutions, mentor junior engineers, and drive technical initiatives to improve platform performance, reliability, and security. Collaborate with cross-functional teams to ensure high-quality code and contribute to shaping the company's technology strategy.",
    technologies: [
      "Vue",
      "React",
      "React Native",
      "Astro",
      "TypeScript",
      "SCSS",
      "BEM Methodology",
      "Design System",
      "Web Components",
      "Lit",
      "Golang",
      "Kotlin",
      "Couchbase",
      "PostgreSQL",
      "Redis",
      "Kafka",
      "Microservice Architecture",
      "Microfrontend Architecture",
      "Docker",
      "Kubernetes",
      "Nginx",
      "Gitlab",
      "CI/CD",
      "Cypress",
      "Playwright",
      "Jest",
      "Vitest",
    ],
  },
  {
    company: "Mindbehind by Insider",
    currentPosition: "Software Engineer",
    period: "October 2019 - July 2021",
    location: "Hybrid",
    description:
      "Lead the frontend development for the renewal of the company's flagship product. Implement modern web development practices using React Hooks, Redux, and Router. Deliver cross-platform mobile applications for iOS and Android using WebView.",
    technologies: [
      "React",
      "React Native",
      "Java",
      "AI Chatbot",
      "Amazon Web Services",
      "Spring Boot",
      "Software as a Service",
    ],
  },
  {
    company: "Yuxek Internet Technologies",
    currentPosition: "Web Application Developer",
    period: "June 2019 - August 2019",
    location: "On-site",
    description:
      "Gained experience in developing web applications using Vue.js.",
    technologies: ["Vue", "ASP.NET Core"],
  },
  {
    company: "Freelancer",
    currentPosition: "Frontend Developer and UI/UX Designer",
    period: "December 2017 - October 2018",
    location: "Remote",
    description:
      "Developed responsive and user-focused web applications for various clients. Designed intuitive UI/UX interfaces to improve user engagement.",
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "UI/UX Design",
      "jQuery",
      "Bootstrap",
      "Wordpress",
      "PHP",
      "User Experience Design (UED)",
      "AJAX",
      "MySQL",
    ],
  },
  {
    company: "Mikrodev Information Technology and Electronics",
    currentPosition: "Intern",
    period: "August 2018 - September 2018",
    location: "On-site",
    description:
      "Gained experience in developing hardware and software solutions.",
    technologies: ["Assembly", "C", "C++", "Computer Architecture"],
  },
  {
    company: "Otokar Automotive and Defense Industries",
    currentPosition: "Intern",
    period: "July 2017 - August 2017",
    location: "On-site",
    description:
      "Gained experience in developing hardware and software solutions.",
    technologies: ["C#", ".NET", "SQL", "MVC", "Entity Framework"],
  },
];

export const educationList: Education[] = [
  {
    school: "Mugla Sitki Kocman University",
    degree: "Master's Degree",
    year: "2021 - Present",
    description: "Digital Game Design and Technologies",
    achievements: [
      "Game Design",
      "Game Development",
      "Game Programming",
      "Game Testing",
      "Game Management",
      "Game Marketing",
      "Game Distribution",
      "Game Analytics",
      "Game Optimization",
      "Game Localization",
      "Game Modding",
    ],
  },
  {
    school: "Anadolu University",
    degree: "Bachelor's Degree",
    year: "2019 - Present",
    description: "Management Information Systems and Services",
    achievements: [
      "Software Development",
      "Project Management",
      "Business Intelligence",
      "Financial Management",
      "Financial Accounting",
      "Management Accounting",
      "Business Law",
      "Business Ethics",
      "Business Communication",
      "Business English",
    ],
  },
  {
    school: "Sakarya University",
    degree: "Bachelor's Degree",
    year: "2015 - 2019",
    description: "Computer Science and Engineering",
    achievements: [
      "Computer Networks",
      "Software Engineering",
      "Database Management",
      "Artificial Intelligence",
      "Computer Graphics",
      "Computer Vision",
      "Machine Learning",
      "Data Structures",
      "Algorithms",
      "Operating Systems",
      "Computer Architecture",
      "Software Testing",
      "Software Quality Assurance",
      "Software Project Management",
      "Software Engineering Ethics",
      "Software Engineering Practices",
      "Software Engineering Principles",
      "Human Computer Interaction",
      "Hardware Architecture",
      "Computer Networks",
      "Computer Security",
      "Computer Forensics",
      "Computer Ethics",
    ],
  },
  {
    school: "Florya Tevfik Ercan Anatolian High School",
    degree: "High School",
    year: "2011 - 2015",
    description: "Mathematics & Science",
    achievements: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Turkish",
      "History",
      "Geography",
      "Civics",
      "Economics",
      "Computer Science",
    ],
  },
];
