import type { SkillCategory } from "~/types/skills";

export const skillCategories: SkillCategory[] = [
  {
    name: "skills.categories.favorites",
    categoryKey: "favorites",
    icon: "lucide:star",
    skills: [
      {
        name: "skills.items.vue.name",
        description: "skills.items.vue.description",
        skillKey: "vue",
        icon: "simple-icons:vuedotjs",
      },
      {
        name: "skills.items.nuxt.name",
        description: "skills.items.nuxt.description",
        skillKey: "nuxt",
        icon: "simple-icons:nuxt",
      },
      {
        name: "skills.items.typescript.name",
        description: "skills.items.typescript.description",
        skillKey: "typescript",
        icon: "simple-icons:typescript",
      },
      {
        name: "skills.items.vite.name",
        description: "skills.items.vite.description",
        skillKey: "vite",
        icon: "simple-icons:vite",
      },
      {
        name: "skills.items.bun.name",
        description: "skills.items.bun.description",
        skillKey: "bun",
        icon: "simple-icons:bun",
      },
      {
        name: "skills.items.lit.name",
        description: "skills.items.lit.description",
        skillKey: "lit",
        icon: "simple-icons:lit",
      },
      {
        name: "skills.items.bem.name",
        description: "skills.items.bem.description",
        skillKey: "bem",
        icon: "simple-icons:bem",
      },
      {
        name: "skills.items.hono.name",
        description: "skills.items.hono.description",
        skillKey: "hono",
        icon: "simple-icons:hono",
      },
      {
        name: "skills.items.supabase.name",
        description: "skills.items.supabase.description",
        skillKey: "supabase",
        icon: "simple-icons:supabase",
      },
      {
        name: "skills.items.drizzle.name",
        description: "skills.items.drizzle.description",
        skillKey: "drizzle",
        icon: "simple-icons:drizzle",
      },
      {
        name: "skills.items.cloudflare.name",
        description: "skills.items.cloudflare.description",
        skillKey: "cloudflare",
        icon: "simple-icons:cloudflare",
      },
      {
        name: "skills.items.vercel.name",
        description: "skills.items.vercel.description",
        skillKey: "vercel",
        icon: "simple-icons:vercel",
      },
      {
        name: "skills.items.vitest.name",
        description: "skills.items.vitest.description",
        skillKey: "vitest",
        icon: "simple-icons:vitest",
      },
      {
        name: "skills.items.cypress.name",
        description: "skills.items.cypress.description",
        skillKey: "cypress",
        icon: "simple-icons:cypress",
      },
    ],
  },
  {
    name: "skills.categories.frontendDevelopment",
    categoryKey: "frontendDevelopment",
    icon: "lucide:panel-top",
    skills: [
      {
        name: "skills.items.vue.name",
        description: "skills.items.vue.description",
        skillKey: "vue",
        icon: "simple-icons:vuedotjs",
      },
      {
        name: "skills.items.nuxt.name",
        description: "skills.items.nuxt.description",
        skillKey: "nuxt",
        icon: "simple-icons:nuxt",
      },
      {
        name: "skills.items.react.name",
        description: "skills.items.react.description",
        skillKey: "react",
        icon: "simple-icons:react",
      },
      {
        name: "skills.items.next.name",
        description: "skills.items.next.description",
        skillKey: "next",
        icon: "simple-icons:nextdotjs",
      },
      {
        name: "skills.items.typescript.name",
        description: "skills.items.typescript.description",
        skillKey: "typescript",
        icon: "simple-icons:typescript",
      },
      {
        name: "skills.items.tailwind.name",
        description: "skills.items.tailwind.description",
        skillKey: "tailwind",
        icon: "simple-icons:tailwindcss",
      },
      {
        name: "skills.items.styledComponents.name",
        description: "skills.items.styledComponents.description",
        skillKey: "styledComponents",
        icon: "simple-icons:styledcomponents",
      },
      {
        name: "skills.items.bem.name",
        description: "skills.items.bem.description",
        skillKey: "bem",
        icon: "simple-icons:bem",
      },
      {
        name: "skills.items.sass.name",
        description: "skills.items.sass.description",
        skillKey: "sass",
        icon: "simple-icons:sass",
      },
      {
        name: "skills.items.bun.name",
        description: "skills.items.bun.description",
        skillKey: "bun",
        icon: "simple-icons:bun",
      },
      {
        name: "skills.items.pnpm.name",
        description: "skills.items.pnpm.description",
        skillKey: "pnpm",
        icon: "simple-icons:pnpm",
      },
      {
        name: "skills.items.lit.name",
        description: "skills.items.lit.description",
        skillKey: "lit",
        icon: "simple-icons:lit",
      },
      {
        name: "skills.items.vitest.name",
        description: "skills.items.vitest.description",
        skillKey: "vitest",
        icon: "simple-icons:vitest",
      },
      {
        name: "skills.items.jest.name",
        description: "skills.items.jest.description",
        skillKey: "jest",
        icon: "simple-icons:jest",
      },
      {
        name: "skills.items.cypress.name",
        description: "skills.items.cypress.description",
        skillKey: "cypress",
        icon: "simple-icons:cypress",
      },
      {
        name: "skills.items.playwright.name",
        description: "skills.items.playwright.description",
        skillKey: "playwright",
        icon: "simple-icons:playwright",
      },
    ],
  },
  {
    name: "skills.categories.backendDevelopment",
    categoryKey: "backendDevelopment",
    icon: "mdi:server",
    skills: [
      {
        name: "skills.items.hono.name",
        description: "skills.items.hono.description",
        skillKey: "hono",
        icon: "simple-icons:hono",
      },
      {
        name: "skills.items.nodejs.name",
        description: "skills.items.nodejs.description",
        skillKey: "nodejs",
        icon: "simple-icons:nodedotjs",
      },
      {
        name: "skills.items.express.name",
        description: "skills.items.express.description",
        skillKey: "express",
        icon: "simple-icons:express",
      },
      {
        name: "skills.items.mongodb.name",
        description: "skills.items.mongodb.description",
        skillKey: "mongodb",
        icon: "simple-icons:mongodb",
      },
      {
        name: "skills.items.postgresql.name",
        description: "skills.items.postgresql.description",
        skillKey: "postgresql",
        icon: "simple-icons:postgresql",
      },
      {
        name: "skills.items.mysql.name",
        description: "skills.items.mysql.description",
        skillKey: "mysql",
        icon: "simple-icons:mysql",
      },
      {
        name: "skills.items.drizzle.name",
        description: "skills.items.drizzle.description",
        skillKey: "drizzle",
        icon: "simple-icons:drizzle",
      },
      {
        name: "skills.items.go.name",
        description: "skills.items.go.description",
        skillKey: "go",
        icon: "simple-icons:go",
      },
    ],
  },
  {
    name: "skills.categories.devops",
    categoryKey: "devops",
    icon: "mdi:cloud",
    skills: [
      {
        name: "skills.items.docker.name",
        description: "skills.items.docker.description",
        skillKey: "docker",
        icon: "simple-icons:docker",
      },
      {
        name: "skills.items.nginx.name",
        description: "skills.items.nginx.description",
        skillKey: "nginx",
        icon: "simple-icons:nginx",
      },
      {
        name: "skills.items.vercel.name",
        description: "skills.items.vercel.description",
        skillKey: "vercel",
        icon: "simple-icons:vercel",
      },
      {
        name: "skills.items.cloudflare.name",
        description: "skills.items.cloudflare.description",
        skillKey: "cloudflare",
        icon: "simple-icons:cloudflare",
      },
      {
        name: "skills.items.linux.name",
        description: "skills.items.linux.description",
        skillKey: "linux",
        icon: "simple-icons:linux",
      },
      {
        name: "skills.items.git.name",
        description: "skills.items.git.description",
        skillKey: "git",
        icon: "simple-icons:git",
      },
      {
        name: "skills.items.github.name",
        description: "skills.items.github.description",
        skillKey: "github",
        icon: "simple-icons:github",
      },
      {
        name: "skills.items.githubActions.name",
        description: "skills.items.githubActions.description",
        skillKey: "githubActions",
        icon: "simple-icons:githubactions",
      },
      {
        name: "skills.items.gitlab.name",
        description: "skills.items.gitlab.description",
        skillKey: "gitlab",
        icon: "simple-icons:gitlab",
      },
    ],
  },
  {
    name: "skills.categories.ai",
    categoryKey: "ai",
    icon: "lucide:brain",
    skills: [
      {
        name: "skills.items.chatgpt.name",
        description: "skills.items.chatgpt.description",
        skillKey: "chatgpt",
        icon: "simple-icons:openai",
      },
      {
        name: "skills.items.claude.name",
        description: "skills.items.claude.description",
        skillKey: "claude",
        icon: "simple-icons:claude",
      },
      {
        name: "skills.items.cursor.name",
        description: "skills.items.cursor.description",
        skillKey: "cursor",
        icon: "lucide:brain",
      },
      {
        name: "skills.items.v0.name",
        description: "skills.items.v0.description",
        skillKey: "v0",
        icon: "simple-icons:v0",
      },
      {
        name: "skills.items.githubCopilot.name",
        description: "skills.items.githubCopilot.description",
        skillKey: "githubCopilot",
        icon: "simple-icons:github",
      },
      {
        name: "skills.items.gemini.name",
        description: "skills.items.gemini.description",
        skillKey: "gemini",
        icon: "simple-icons:google",
      },
      {
        name: "skills.items.grok.name",
        description: "skills.items.grok.description",
        skillKey: "grok",
        icon: "simple-icons:x",
      },
    ],
  },
  {
    name: "skills.categories.design",
    categoryKey: "design",
    icon: "lucide:palette",
    skills: [
      {
        name: "skills.items.figma.name",
        description: "skills.items.figma.description",
        skillKey: "figma",
        icon: "simple-icons:figma",
      },
      {
        name: "skills.items.adobeXd.name",
        description: "skills.items.adobeXd.description",
        skillKey: "adobeXd",
        icon: "simple-icons:adobexd",
      },
      {
        name: "skills.items.canva.name",
        description: "skills.items.canva.description",
        skillKey: "canva",
        icon: "simple-icons:canva",
      },
    ],
  },
  {
    name: "skills.categories.languages",
    categoryKey: "languages",
    icon: "lucide:earth",
    skills: [
      {
        name: "skills.items.turkish.name",
        description: "skills.items.turkish.description",
        skillKey: "turkish",
        icon: "circle-flags:tr",
      },
      {
        name: "skills.items.english.name",
        description: "skills.items.english.description",
        skillKey: "english",
        icon: "circle-flags:us",
      },
      {
        name: "skills.items.german.name",
        description: "skills.items.german.description",
        skillKey: "german",
        icon: "circle-flags:de",
      },
    ],
  },
];
